- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name: Check if Docker is installed
  command: docker --version
  register: docker_check
  ignore_errors: yes

  - name: Install Docker
  apt:
    name: docker.io
    state: present
  when: docker_check.failed

  - name: Check if Docker service is running
  command: systemctl is-active docker
  register: docker_service_status
  ignore_errors: yes

- name: Start Docker Service
  command: sudo systemctl start docker
  when: docker_service_status.stdout != 'active'

# This will alway remove the containers so that we will not get port already used error.
  - name: Remove all Docker containers
    shell: |
      sudo docker rm -f $(sudo docker ps -aq)

  - name : Start Docker Service
    command : sudo docker run -dt -p 8081:8081 --name finance-project soumyaranjanrout0/finance-image:v1

