- name : Configure Docker on EC2 Instances
  hosts : all
  become: true
  connection : ssh
  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io

  - name : Start Docker Service
    command : sudo systemctl start docker
# This will alway remove the containers so that we will not get port already used error.
  - name : Remove all container
    command : sudo docker rm -f $(docker ps -aq)

  - name : Start Docker Service
    command : sudo docker run -dt -p 8081:8081 --name finance-project soumyaranjanrout0/finance-image:v1

